### ISSUE TITLE
The codes for CAT

### ISSUE THREAD

**Issue by ffeng1017** [ZixuanKe/CAT#1]
Thanks for the nice work!

I am wondering which file is the implementation of the proposed CAT. Would you mind indicating it?

**Comment by ZixuanKe** [comment]
Hi ffeng,

Thank you for your interest in our work. I updated the name convention and hopefully it would be clearer.

Specifically, to run (f-emnist, emnist-10) with CAT, please run the “run_train_mixemnist_mlp_cat_10_10_ncl.sh” 

Feel free to let me know if you have any other questions.
Zixuan

**Comment by ffeng1017** [comment]
Got it. Thanks a lot for taking the time!
