### ISSUE TITLE
Adopt f_{KTA} in test phase

### ISSUE THREAD

**Issue by WenjinW** [ZixuanKe/CAT#2]
Thanks for the nice work!

The paper claims that the classifier f_{KTA} is used in testing, and f_{mask} is only used in testing when the task t has no similar previous tasks. But the h_{KTA}^t does not contain the information in h_{mask}^t. Does this mean that in the test phase, task t can only use the parameters of similar tasks, without its own additional parameters?

**Comment by ZixuanKe** [comment]
Thanks for your interest in our work! I am sorry for the late reply!
It is true that we didn't use task t's own additional parameters in f_{KTA}. Feel free to try it and it could be helpful.
