### ISSUE TITLE
A strange question

### ISSUE THREAD

**Issue by wangzhe112-lab** [ZixuanKe/CAT#3]
![image](https://user-images.githubusercontent.com/56470984/146903807-75b00146-3ceb-4040-8e5d-44b98975d00b.png)

I don't know what caused it

**Comment by ZixuanKe** [comment]
Hi,
 
Thank you for your interest in our project. 
 
It seems to me your pytorch is not installed correctly. I guess you can try follow the [PyContinual](https://github.com/ZixuanKe/PyContinual/blob/main/docs/run_exist.md) to install the needed package and test again
 
Thank you for your time,
Zixuan

**Comment by wangzhe112-lab** [comment]
Thank you very much for your help.
